# This is a basic workflow to help you get started with Actions

name: traffic-stats

# Controls when the workflow will run
on:
  #schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    #- cron: "0 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  csv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout csv
        run: git restore --source csv -- traffic_2022.csv
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Create CSV
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Commit csv
        run: |
          git config user.name github-actions
          git config user.email "<>"
          git add traffic_2022.csv
          git commit -m "generated"
          git push origin ${{ github.ref_name }}:csv
      